src/Entity/Trading.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass="App\Repository\TradingRepository")
 */
class Trading {

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"trading", "offer"})
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Groups({"trading", "offer"})
     */
    private $name;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", cascade={"persist"})
     * @Groups({"trading", "offer"})
     */
    private $location;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $completeAddress;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $streetNumber;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $route;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"trading", "offer"})
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @Groups({"trading", "offer"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Offer", mappedBy="trading", cascade={"persist"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     * @Groups({"trading"})
     */
    private $offers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="tradings")
     * @Groups({"trading"})
     */
    private $users;

    public function __construct() {
        $this->offers = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void {
        $this->id = $id;
    }


    /**
     * @return mixed
     */
    public function getName() {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void {
        $this->name = $name;
    }

    /**
     * @return \App\Entity\Location
     */
    public function getLocation() {
        return $this->location;
    }

    /**
     * @param \App\Entity\Location $location
     */
    public function setLocation($location): void {
        $this->location = $location;
    }


    /**
     * @return ArrayCollection
     */
    public function getOffers() {
        return $this->offers;
    }

    public function addOffer(Offer $offer) {
        $this->offers[] = $offer;
    }

    public function removeOffer(Trading $offer) {
        $this->offers->removeElement($offer);
    }

    /**
     * @return mixed
     */
    public function getUser() {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void {
        $this->user = $user;
    }

    /**
     * @return ArrayCollection
     */
    public function getUsers() {
        return $this->users;
    }

    /**
     * @param mixed $users
     */
    public function setUsers($users): void {
        $this->users = $users;
    }

    public function addUser(User $user) {
        $this->users[] = $user;
    }

    public function removeUser(Trading $user) {
        $this->users->removeElement($user);
    }

    /**
     * @return mixed
     */
    public function getCompleteAddress() {
        return $this->completeAddress;
    }

    /**
     * @param mixed $completeAddress
     */
    public function setCompleteAddress($completeAddress): void {
        $this->completeAddress = $completeAddress;
    }

    /**
     * @return mixed
     */
    public function getLongitude() {
        return $this->longitude;
    }

    /**
     * @param mixed $longitude
     */
    public function setLongitude($longitude): void {
        $this->longitude = $longitude;
    }

    /**
     * @return mixed
     */
    public function getStreetNumber() {
        return $this->streetNumber;
    }

    /**
     * @param mixed $streetNumber
     */
    public function setStreetNumber($streetNumber): void {
        $this->streetNumber = $streetNumber;
    }

    /**
     * @return mixed
     */
    public function getRoute() {
        return $this->route;
    }

    /**
     * @param mixed $route
     */
    public function setRoute($route): void {
        $this->route = $route;
    }

    /**
     * @return mixed
     */
    public function getLatitude() {
        return $this->latitude;
    }

    /**
     * @param mixed $latitude
     */
    public function setLatitude($latitude): void {
        $this->latitude = $latitude;
    }

    /**
     * @return mixed
     */
    public function getPostalCode() {
        return $this->postalCode;
    }

    /**
     * @param mixed $postalCode
     */
    public function setPostalCode($postalCode): void {
        $this->postalCode = $postalCode;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(uniqueConstraints={@ORM\UniqueConstraint(name="user_email_unique",columns={"email"})})
 */
class User implements UserInterface {
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"user", "auth-token", "group", "notif", "trading"})
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * @Groups({"user", "auth-token", "group", "notif", "trading", "offer"})
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Groups({"user", "auth-token", "group", "notif", "trading", "offer"})
     */
    private $lastname;

    /**
     * @ORM\Column(type="string")
     * @Groups({"user", "auth-token", "trading", "offer"})
     */
    private $email;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    private $plainPassword;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups({"user", "auth-token"})
     */
    private $dateOfBirth;


    /**
     * @ORM\Column(type="string")
     * @Groups({"user", "auth-token", "group", "notif", "trading", "offer"})
     * @var string
     */
    private $picture;

    /**
     * @ORM\Column(type="boolean",nullable=true)
     * @Groups({"user", "auth-token"})
     * @var bool
     */
    private $authWithGoogle = false;

    /**
     * @ORM\Column(type="array")
     * @Groups({"user", "auth-token"})
     */
    private $roles = ['ROLE_USER'];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Interest", inversedBy="users",cascade={"persist"})
     * @Groups({"user", "auth-token"})
     */
    private $interests;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Trading", inversedBy="users", cascade={"persist"})
     */
    private $tradings;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", cascade={"persist"})
     * @Groups({"user", "auth-token"})
     */
    private $location;

    /**
     * Les groupes dont l'utilisateur est l'admin
     * @ORM\OneToMany(targetEntity="SocialGroup", mappedBy="admin")
     */
    private $createdGroups;

    /**
     * Les groupes dont fait partie l'utilisateur
     * @ORM\ManyToMany(targetEntity="SocialGroup", inversedBy="members")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $groups;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="recipient", cascade={"persist"})
     */
    private $notifications;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string Firebase Cloud Messaging token
     * @Groups({"user", "auth-token"})
     */
    private $fcmToken;

    public function __construct() {
        $this->interests = new ArrayCollection();
        $this->tradings = new ArrayCollection();
        $this->tradings = new ArrayCollection();
        $this->createdGroups = new ArrayCollection();
        $this->groups = new ArrayCollection();
        $this->notifications = new ArrayCollection();

        $this->picture = "default-profile.png";
    }

    /**
     * @return mixed
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getFirstname() {
        return $this->firstname;
    }

    /**
     * @param mixed $firstname
     */
    public function setFirstname($firstname): void {
        $this->firstname = $firstname;
    }

    /**
     * @return mixed
     */
    public function getLastname() {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname): void {
        $this->lastname = $lastname;
    }

    /**
     * @return mixed
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getPassword() {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getDateOfBirth() {
        return $this->dateOfBirth;
    }

    /**
     * @param mixed $dateOfBirth
     */
    public function setDateOfBirth($dateOfBirth): void {
        $this->dateOfBirth = $dateOfBirth;
    }

    /**
     * @return mixed
     */
    public function getPlainPassword() {
        return $this->plainPassword;
    }

    /**
     * @param mixed $plainPassword
     */
    public function setPlainPassword($plainPassword): void {
        $this->plainPassword = $plainPassword;
    }


    /**
     * @return string
     */
    public function getPicture(): string {
        return $this->picture;
    }

    /**
     * @param string $picture
     */
    public function setPicture(string $picture): void {
        $this->picture = $picture;
    }

    /**
     * @return bool
     */
    public function isAuthWithGoogle(): bool {
        return $this->authWithGoogle;
    }

    /**
     * @param bool $authWithGoogle
     */
    public function setAuthWithGoogle(bool $authWithGoogle): void {
        $this->authWithGoogle = $authWithGoogle;
    }


    public function getRoles() {
        return $this->roles;
    }

    /**
     * @param mixed $roles
     */
    public function setRoles($roles): void {
        $this->roles = $roles;
    }

    /**
     * @return ArrayCollection
     */
    public function getInterests() {
        return $this->interests;
    }

    /**
     * @return ArrayCollection
     */
    public function getTradings() {
        return $this->tradings;
    }

    /**
     * @param mixed $interests
     */
    public function setInterests($interests): void {
        $this->interests = $interests;
    }


    public function addInterest(Interest $interest) {
        $this->interests[] = $interest;
        $interest->addUser($this);
    }

    public function removeInterest(Interest $interest) {
        $this->interests->removeElement($interest);
        $interest->removeUser($this);
    }


    /**
     * @return \App\Entity\Location
     */
    public function getLocation() {
        return $this->location;
    }

    /**
     * @param mixed
     */
    public function setLocation($location) {
        $this->location = $location;
    }


    public function addTrading(Trading $trading) {
        $this->tradings[] = $trading;
    }

    public function removeTrading(Trading $trading) {
        $this->tradings->removeElement($trading);
    }

    /**
     * @return ArrayCollection
     */
    public function getCreatedGroups() {
        return $this->createdGroups;
    }

    /**
     * @return mixed
     */
    public function getGroups() {
        return $this->groups;
    }


    public function addCreatedGroup(SocialGroup $group) {
        $this->createdGroups[] = $group;
    }

    public function removeCreatedGroup(SocialGroup $group) {
        $this->createdGroups->removeElement($group);
    }

    public function addGroup(SocialGroup $group) {
        $this->groups[] = $group;
    }

    public function removeGroup(SocialGroup $group) {
        $this->groups->removeElement($group);
    }


    public function addNotification(Notification $notification) {
        $this->notifications[] = $notification;
    }

    public function removeNotification(Notification $notification) {
        $this->notifications->removeElement($notification);
    }

    /**
     * @return ArrayCollection
     */
    public function getNotifications() {
        return $this->notifications;
    }


    public function getSalt() {
        return null;
    }

    public function getUsername() {
        return $this->email;
    }

    public function eraseCredentials() {
        // Suppression des données sensibles
        $this->plainPassword = null;
    }

    protected function getUploadRootDir() {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return dirname(__FILE__, 3) . '/public/img';
    }

    public function getWebPath() {
        return $this->getUploadRootDir() . '/' . $this->getPicture();
    }

    /**
     * @return string
     */
    public function getFcmToken(): ?string {
        return $this->fcmToken;
    }

    /**
     * @param string $fcmToken
     */
    public function setFcmToken(string $fcmToken): void {
        $this->fcmToken = $fcmToken;
    }

    public function containsTrading($id): bool {
        foreach ($this->getTradings() as $trading) {
            if ($trading->getId() == $id) {
                return true;
            }
        }
        return false;
    }
}

src/Form/TradingType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Trading;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TradingType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('id', null, ['required' => false])
            ->add('name', TextType::class, ['attr' => ['class' => 'form-control mb-2']])
            ->add('completeAddress', TextType::class, [
                'required' => true,
                'label' => 'Adresse'
            ])
            ->add('streetNumber', TextType::class, [
                'required' => false,
                'label' => false,
                'attr' => ['hidden' => true]
            ])
            ->add('route', TextType::class, [
                'required' => false,
                'label' => false,
                'attr' => ['hidden' => true]
            ])
            ->add('postalCode', TextType::class, [
                'required' => false,
                'label' => false,
                'attr' => ['hidden' => true]
            ])
            ->add('latitude', TextType::class, [
                'required' => false,
                'label' => false,
                'attr' => ['hidden' => true]
            ])
            ->add('longitude', TextType::class, [
                'required' => false,
                'label' => false,
                'attr' => ['hidden' => true]
            ])
            ->add('location', LocationType::class, [
                'label' => false,
                'attr' => ['id' => 'location', 'hidden' => true],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            // uncomment if you want to bind to a class
            'data_class' => Trading::class,
            'csrf_protection' => false
        ]);
    }
}

templates/trading/add.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   <div class="row">
       <div class="col-md-6 mx-auto">
           <h1>Ajouter un commerce</h1>
           {{ form_start(form, {'attr': {'autocomplete': 'off'}}) }}
           {{ form_widget(form) }}
           {{ form_end(form) }}
       </div>
   </div>
{% endblock %}

templates/trading/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            {{ form_start(form, {'attr': {'autocomplete': 'off'}}) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/trading/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <h1>Commerces</h1>
            {% if tradings %}
                <table class="table table-striped table-responsive-md">
                    <thead>
                    <tr>
                        <th>Commerces</th>
                        <th>Offres</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for trading in tradings %}
                        <tr>
                            <td>{{ trading.name }} <span class="small"><em>{{ trading.completeAddress }}</em></span></td>
                            <td>{{ trading.offers|length }}</td>
                            <td>
                                <a href="{{ path('show_trading', {'id':trading.id}) }}" class="btn btn-dark">Voir</a>
                                <a href="{{ path('edit_trading', {'id':trading.id}) }}"
                                   class="btn btn-primary">Modifier</a>
                                <a href="{{ path('delete_trading', {'id':trading.id}) }}"
                                   class="btn btn-danger" data-id="{{ trading.id }}">Supprimer</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Pas d'articles</p>
            {% endif %}
            <div class="navigation text-center">
                {{ pagerfanta(tradings, 'twitter_bootstrap4_translated', {routeName: 'tradings_index_paginated'}) }}
            </div>
        </div>
        <div class="col-md-2">
            <a href="{{ path('add_trading') }}" class="btn btn-success btn-block"><i class="fas fa-plus-circle"></i> Ajouter</a>
        </div>
    </div>
{% endblock %}

templates/trading/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            {% if trading.offers | length > 0 %}
                <table class="table table-striped table-responsive-md">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Produit</th>
                        <th>Marque</th>
                        <th>Prix</th>
                        <th>Catégorie</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for offer in offers %}
                        <tr>
                            <td>
                                <img src="{{ asset(offer.webPath) }}" alt="offer-img" class="img-thumbnail" width="100" height="100">
                            </td>
                            <td>{{ offer.product | capitalize }}</td>
                            <td>{{ offer.brand }}</td>
                            <td>{{ offer.price }}</td>
                            <td>{{ offer.category.category | capitalize }}</td>
                            <td>
                                <a href="{{ path('edit_offer', {'id': trading.id,'offer_id':offer.id}) }}"
                                   class="btn btn-primary">Modifier</a>
                                <a href="{{ path('delete_offer', {'id': trading.id,'offer_id':offer.id}) }}"
                                   class="btn btn-danger" data-id="{{ offer.id }}">Supprimer</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Pas d'offres</p>
            {% endif %}
            {% if offers.haveToPaginate %}
                <div class="navigation text-center">
                    {{ pagerfanta(offers, 'twitter_bootstrap4_translated', {routeName: 'offers_index_paginated', routeParams: {'id': trading.id}}) }}
                </div>
            {% endif %}
        </div>
        <div class="col-md-2">
            <a href="{{ path('add_offer', {'id': trading.id}) }}" class="btn btn-success btn-block"><i
                        class="fas fa-plus-circle"></i>
                Ajouter</a>
        </div>
    </div>
{% endblock %}